# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.cache/wt [current_project]
set_property parent.project_path C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/pal24bit.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/RedSoul.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/San.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/SanPal.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/cursor.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/colorbar.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/Title.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/TitlePal.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/ColorbarPal.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/Win.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/Gameover.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/WinPal.mem
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/GameoverPal.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/BallSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/BallSprite2.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/BallSprite3.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/ColorbarRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/ColorbarSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/CursorRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/CursorSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/FightFrameSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/FrameSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/GameoverRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/GameoverSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/Hp2Sprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/HpSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/PS2Receiver.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/PivotSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/SanRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/SanSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/SoulRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/SoulSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/TimerState.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/TitleRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/TitleSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/WinRom.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/WinSprite.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/clkDivide.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/debouncer.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/keyboard.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/segmentDriver.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/vga640x480.v
  C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/sources_1/new/Top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files C:/Users/Nai/Desktop/one-credit-undertales/AHam/AHam.srcs/constrs_1/new/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
